# Generated by Django 4.1.5 on 2023-01-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_remove_pizzamodel_increments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(default=1, upload_to='pizzas'),
            preserve_default=False,
        ),
    ]
